import type { BasicInfo } from "@/types/Charts";
import { SVG_SRC } from "./svg";
import { IMG_SRC } from "./image";

export const CHARTS_IMG: Record<string, string> = {
  "000001": SVG_SRC["000001"],
  IXIC: SVG_SRC["IXIC"],
  USDCNH: IMG_SRC["USDCNH"],
  BTCUSD: IMG_SRC["BTCUSDT"],
  ETHUSD: IMG_SRC["ETHUSDT"],
  XAUUSD: IMG_SRC["AU888"],
  AU888: IMG_SRC["AU888"],
  XAUCNY: IMG_SRC["AU888"],
  AG888: SVG_SRC["AG888"],
  XAGCNY: SVG_SRC["AG888"],
  "600519": SVG_SRC["600519"],
  "399300": SVG_SRC["399300"],
  "399905": SVG_SRC["399905"],
  SH: IMG_SRC["SH"], // 上海证券交易所
  L1: IMG_SRC["L1"], // Level1 基础行情
  WH: IMG_SRC["WH"], // 外汇
  US: IMG_SRC["US"],
  NLS: IMG_SRC["NLS"],
  XAUTUSDT: IMG_SRC["XAUTUSDT"],
  币安人生USDT: IMG_SRC["币安人生USDT"],
  BTCUSDT: IMG_SRC["BTCUSDT"],
  ETHUSDT: IMG_SRC["ETHUSDT"],
};

export const GUSHITONG_MARKET: Record<string, string> = {
  ab: "A股",
  us: "美股",
  global: "全球",
};

export const basicInfoMap: Record<string, BasicInfo> = {
  "000001": {
    precision: 4,
    code: "000001",
    exchange: "SZ",
    logo: CHARTS_IMG["000001"],
    name: "上证指数",
    provider: "东方财富",
    tagList: [
      {
        desc: "上海证券交易所",
        imageUrl: CHARTS_IMG["SH"],
      },
      {
        desc: "Level1 基础行情",
        imageUrl: CHARTS_IMG["L1"],
      },
    ],
    timestamp: undefined,
    time: undefined,
    price: undefined,
    increase: undefined,
    ratio: undefined,
    volume: undefined,
    datetime: undefined,
    tradeStatusCN: undefined,
  },
  AU888: {
    precision: 4,
    code: "AU888",
    exchange: "FT",
    logo: CHARTS_IMG["AU888"],
    name: "黄金",
    provider: "东方财富",
    tagList: [
      {
        desc: "上海期货交易所",
        imageUrl: CHARTS_IMG["SH"],
      },
      {
        desc: "Level1 基础行情",
        imageUrl: CHARTS_IMG["L1"],
      },
    ],
    timestamp: undefined,
    time: undefined,
    price: undefined,
    increase: undefined,
    ratio: undefined,
    volume: undefined,
    datetime: undefined,
    tradeStatusCN: undefined,
  },
  XAUCNY: {
    precision: 4,
    code: "XAUCNY",
    exchange: "FX",
    logo: CHARTS_IMG["XAUCNY"],
    name: "黄金",
    provider: "",
    tagList: [
      {
        desc: "外汇",
        imageUrl: CHARTS_IMG["WH"],
      },
      {
        desc: "Level1 基础行情",
        imageUrl: CHARTS_IMG["L1"],
      },
    ],
    timestamp: undefined,
    time: undefined,
    price: undefined,
    increase: undefined,
    ratio: undefined,
    volume: undefined,
    datetime: undefined,
    tradeStatusCN: undefined,
  },
  AG888: {
    precision: 4,
    code: "AG888",
    exchange: "FT",
    logo: CHARTS_IMG["AG888"],
    name: "白银",
    provider: "东方财富",
    tagList: [
      {
        desc: "上海期货交易所",
        imageUrl: CHARTS_IMG["SH"],
      },
      {
        desc: "Level1 基础行情",
        imageUrl: CHARTS_IMG["L1"],
      },
    ],
    timestamp: undefined,
    time: undefined,
    price: undefined,
    increase: undefined,
    ratio: undefined,
    volume: undefined,
    datetime: undefined,
    tradeStatusCN: undefined,
  },
  XAGCNY: {
    precision: 4,
    code: "XAGCNY",
    exchange: "FT",
    logo: CHARTS_IMG["XAGCNY"],
    name: "白银",
    provider: "",
    tagList: [
      {
        desc: "外汇",
        imageUrl: CHARTS_IMG["WH"],
      },
      {
        desc: "Level1 基础行情",
        imageUrl: CHARTS_IMG["L1"],
      },
    ],
    timestamp: undefined,
    time: undefined,
    price: undefined,
    increase: undefined,
    ratio: undefined,
    volume: undefined,
    datetime: undefined,
    tradeStatusCN: undefined,
  },
  IXIC: {
    precision: 4,
    code: "IXIC",
    exchange: "US",
    logo: CHARTS_IMG["IXIC"],
    name: "纳斯达克",
    provider: "东方财富",
    tagList: [
      {
        desc: "自定义市场-美指",
        imageUrl: CHARTS_IMG["US"],
      },
      {
        desc: "NLS基础行情",
        imageUrl: CHARTS_IMG["NLS"],
      },
    ],
    timestamp: undefined,
    time: undefined,
    price: undefined,
    increase: undefined,
    ratio: undefined,
    volume: undefined,
    datetime: undefined,
    tradeStatusCN: undefined,
  },
  "600519": {
    precision: 4,
    code: "600519",
    exchange: "SH",
    logo: CHARTS_IMG["600519"],
    name: "贵州茅台",
    provider: "东方财富",
    tagList: [
      {
        desc: "上海交易所",
        imageUrl: CHARTS_IMG["SH"],
      },
      {
        desc: "Level1基础行情",
        imageUrl: CHARTS_IMG["L1"],
      },
    ],
    timestamp: undefined,
    time: undefined,
    price: undefined,
    increase: undefined,
    ratio: undefined,
    volume: undefined,
    datetime: undefined,
    tradeStatusCN: undefined,
  },
  USDCNH: {
    precision: 4,
    code: "USDCNH",
    exchange: "FX",
    logo: CHARTS_IMG["USDCNH"],
    name: "美元兑中国离岸人民币",
    provider: "",
    tagList: [
      {
        desc: "外汇",
        imageUrl: CHARTS_IMG["WH"],
      },
      {
        desc: "Level1基础行情",
        imageUrl: CHARTS_IMG["L1"],
      },
    ],
    timestamp: undefined,
    time: undefined,
    price: undefined,
    increase: undefined,
    ratio: undefined,
    volume: undefined,
    datetime: undefined,
    tradeStatusCN: undefined,
  },
  币安人生USDT: {
    precision: 4,
    code: "币安人生USDT",
    exchange: "Binance",
    logo: CHARTS_IMG["币安人生USDT"],
    name: "币安人生",
    provider: "",
    tagList: [],
    timestamp: undefined,
    time: undefined,
    price: undefined,
    increase: undefined,
    ratio: undefined,
    volume: undefined,
    datetime: undefined,
    tradeStatusCN: undefined,
  },
  BTCUSDT: {
    precision: 1,
    code: "BTCUSDT",
    exchange: "Binance",
    logo: CHARTS_IMG["BTCUSDT"],
    name: "比特币",
    provider: "",
    tagList: [],
    timestamp: undefined,
    time: undefined,
    price: undefined,
    increase: undefined,
    ratio: undefined,
    volume: undefined,
    datetime: undefined,
    tradeStatusCN: undefined,
  },
  ETHUSDT: {
    precision: 1,
    code: "ETHUSDT",
    exchange: "Bitget",
    logo: CHARTS_IMG["ETHUSDT"],
    name: "以太坊",
    provider: "",
    tagList: [],
    timestamp: undefined,
    time: undefined,
    price: undefined,
    increase: undefined,
    ratio: undefined,
    volume: undefined,
    datetime: undefined,
    tradeStatusCN: undefined,
  },
  XAUTUSDT: {
    precision: 1,
    code: "XAUTUSDT",
    exchange: "Bitget",
    logo: CHARTS_IMG["XAUTUSDT"],
    name: "黄金",
    provider: "",
    tagList: [],
    timestamp: undefined,
    time: undefined,
    price: undefined,
    increase: undefined,
    ratio: undefined,
    volume: undefined,
    datetime: undefined,
    tradeStatusCN: undefined,
  },
};
