export const SVG_SRC: Record<string, string> = {
	binance: "https://arweave.net/aQNyKNtNCRgYJVAxmarQbkvS_gQm_vsLymMakfmfs-c",
	bitget: "https://arweave.net/Hz2HGdVT5JjpN8vzWKRvr_EKdiqYlQALTkLv7g4UXvo",
	coinbase: "https://arweave.net/tO9YYZ0EeV37hK9mm117fcgQB5nvG04t3hRssGT7f8U",
	okx: "https://arweave.net/LNKDawZfcTqDeIbUmne4eMRSkBU8f3HBTpxKkcZlAwE",
	ar: "https://arweave.net/OQfzwZk-vFt0B8cAeogFC8dp9SB2ukosI1njCsbZRbo",
	btc: "https://arweave.net/0xDQN3S4ieYNf-CiPbVx8USxlEQDFXnT0q6vpIIcdDE",
	btc1: "https://arweave.net/uoesXSX-0RK-U7ydPGYHm7nsbQG0_x2epfFgeUQgp14",
	eth: "https://arweave.net/6dlNT9F0E6L54YKrb7DQYVvLgtHzrX_LdYbVNTHaELA",
	fil: "https://arweave.net/W_EFrGoYDlzP-Nu0-w4tfaZl2q3-2QSk0aRnJ1Y2ovM",
	metamask: "https://arweave.net/gSVFhswODzbQiZezhtfHxQNgjGHZYwpNzumOprbqHBg",
	uni: "https://arweave.net/JMImfQsPOZStjAtP7Wmv_2vGHUNZLdUPdmoneeSnjeo",
	react: "https://arweave.net/Dt4och0GVQWL1vm13RAPl803aBx5tR4jfmuDzy3m4oE",
	vite: "https://arweave.net/u5EFoXHJq-ZHo5E9fPQi6hz5CSuMHWKecrwq0qoQPmk",
	beta: "https://arweave.net/3GPIrmwEI0qWQPaYKJ7z1Yi9H62MhSbnZ7g3BqfjcNs",
	shadcn: "https://arweave.net/FH9h8vOxry2aNqLs-I3OxxkE9T9CiRlauSF3QYuhEDQ",
	solana: "https://arweave.net/bpp3Bib9HeV82BE8umLvHVvuNWLgE4QRNNNQ4hFg5I0",
	sol: "https://arweave.net/bpp3Bib9HeV82BE8umLvHVvuNWLgE4QRNNNQ4hFg5I0",
	gate: "https://arweave.net/uqo-Pt0HmW8fNx5VNC9qmCl0gmaqQwerhs1mjIGirXg",
};
