/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutValtioRouteImport } from './routes/_layout.valtio'
import { Route as LayoutTextRouteImport } from './routes/_layout.text'
import { Route as LayoutTestsRouteImport } from './routes/_layout.tests'
import { Route as LayoutTablePaginationRouteImport } from './routes/_layout.table-pagination'
import { Route as LayoutTableBasicRouteImport } from './routes/_layout.table-basic'
import { Route as LayoutIconsRouteImport } from './routes/_layout.icons'
import { Route as LayoutGushitongRouteImport } from './routes/_layout.gushitong'
import { Route as LayoutGateGridRouteImport } from './routes/_layout.gate-grid'
import { Route as LayoutFearGreedRouteImport } from './routes/_layout.fear-greed'
import { Route as LayoutCronWorkerRouteImport } from './routes/_layout.cron-worker'
import { Route as LayoutCronLogsRouteImport } from './routes/_layout.cron-logs'
import { Route as LayoutCronJobsRouteImport } from './routes/_layout.cron-jobs'
import { Route as LayoutCronConfigRouteImport } from './routes/_layout.cron-config'
import { Route as LayoutCronApiRouteImport } from './routes/_layout.cron-api'
import { Route as LayoutCoingeckoRouteImport } from './routes/_layout.coingecko'
import { Route as LayoutBitgetSfRouteImport } from './routes/_layout.bitget-sf'
import { Route as LayoutBitgetGridRouteImport } from './routes/_layout.bitget-grid'
import { Route as AuthInvoicesRouteImport } from './routes/_auth.invoices'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthInvoicesIndexRouteImport } from './routes/_auth.invoices.index'
import { Route as LayoutG2TooltipRouteImport } from './routes/_layout.g2.tooltip'
import { Route as LayoutG2SpotRouteImport } from './routes/_layout.g2.spot'
import { Route as LayoutG2SliderRouteImport } from './routes/_layout.g2.slider'
import { Route as LayoutG2MultiAreaRouteImport } from './routes/_layout.g2.multi-area'
import { Route as LayoutG2KlineRouteImport } from './routes/_layout.g2.kline'
import { Route as LayoutG2CandleSticksRouteImport } from './routes/_layout.g2.candle-sticks'
import { Route as LayoutEchartsGushiRouteImport } from './routes/_layout.echarts.gushi'
import { Route as LayoutEchartsCryptoRouteImport } from './routes/_layout.echarts.crypto'
import { Route as LayoutEchartsBtcusdtRouteImport } from './routes/_layout.echarts.btcusdt'
import { Route as AuthInvoicesInvoiceIdRouteImport } from './routes/_auth.invoices.$invoiceId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutValtioRoute = LayoutValtioRouteImport.update({
  id: '/valtio',
  path: '/valtio',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTextRoute = LayoutTextRouteImport.update({
  id: '/text',
  path: '/text',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTestsRoute = LayoutTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTablePaginationRoute = LayoutTablePaginationRouteImport.update({
  id: '/table-pagination',
  path: '/table-pagination',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTableBasicRoute = LayoutTableBasicRouteImport.update({
  id: '/table-basic',
  path: '/table-basic',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutIconsRoute = LayoutIconsRouteImport.update({
  id: '/icons',
  path: '/icons',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGushitongRoute = LayoutGushitongRouteImport.update({
  id: '/gushitong',
  path: '/gushitong',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGateGridRoute = LayoutGateGridRouteImport.update({
  id: '/gate-grid',
  path: '/gate-grid',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFearGreedRoute = LayoutFearGreedRouteImport.update({
  id: '/fear-greed',
  path: '/fear-greed',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCronWorkerRoute = LayoutCronWorkerRouteImport.update({
  id: '/cron-worker',
  path: '/cron-worker',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCronLogsRoute = LayoutCronLogsRouteImport.update({
  id: '/cron-logs',
  path: '/cron-logs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCronJobsRoute = LayoutCronJobsRouteImport.update({
  id: '/cron-jobs',
  path: '/cron-jobs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCronConfigRoute = LayoutCronConfigRouteImport.update({
  id: '/cron-config',
  path: '/cron-config',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCronApiRoute = LayoutCronApiRouteImport.update({
  id: '/cron-api',
  path: '/cron-api',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCoingeckoRoute = LayoutCoingeckoRouteImport.update({
  id: '/coingecko',
  path: '/coingecko',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBitgetSfRoute = LayoutBitgetSfRouteImport.update({
  id: '/bitget-sf',
  path: '/bitget-sf',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBitgetGridRoute = LayoutBitgetGridRouteImport.update({
  id: '/bitget-grid',
  path: '/bitget-grid',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthInvoicesRoute = AuthInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInvoicesIndexRoute = AuthInvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthInvoicesRoute,
} as any)
const LayoutG2TooltipRoute = LayoutG2TooltipRouteImport.update({
  id: '/g2/tooltip',
  path: '/g2/tooltip',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutG2SpotRoute = LayoutG2SpotRouteImport.update({
  id: '/g2/spot',
  path: '/g2/spot',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutG2SliderRoute = LayoutG2SliderRouteImport.update({
  id: '/g2/slider',
  path: '/g2/slider',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutG2MultiAreaRoute = LayoutG2MultiAreaRouteImport.update({
  id: '/g2/multi-area',
  path: '/g2/multi-area',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutG2KlineRoute = LayoutG2KlineRouteImport.update({
  id: '/g2/kline',
  path: '/g2/kline',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutG2CandleSticksRoute = LayoutG2CandleSticksRouteImport.update({
  id: '/g2/candle-sticks',
  path: '/g2/candle-sticks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEchartsGushiRoute = LayoutEchartsGushiRouteImport.update({
  id: '/echarts/gushi',
  path: '/echarts/gushi',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEchartsCryptoRoute = LayoutEchartsCryptoRouteImport.update({
  id: '/echarts/crypto',
  path: '/echarts/crypto',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEchartsBtcusdtRoute = LayoutEchartsBtcusdtRouteImport.update({
  id: '/echarts/btcusdt',
  path: '/echarts/btcusdt',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthInvoicesInvoiceIdRoute = AuthInvoicesInvoiceIdRouteImport.update({
  id: '/$invoiceId',
  path: '/$invoiceId',
  getParentRoute: () => AuthInvoicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/invoices': typeof AuthInvoicesRouteWithChildren
  '/bitget-grid': typeof LayoutBitgetGridRoute
  '/bitget-sf': typeof LayoutBitgetSfRoute
  '/coingecko': typeof LayoutCoingeckoRoute
  '/cron-api': typeof LayoutCronApiRoute
  '/cron-config': typeof LayoutCronConfigRoute
  '/cron-jobs': typeof LayoutCronJobsRoute
  '/cron-logs': typeof LayoutCronLogsRoute
  '/cron-worker': typeof LayoutCronWorkerRoute
  '/fear-greed': typeof LayoutFearGreedRoute
  '/gate-grid': typeof LayoutGateGridRoute
  '/gushitong': typeof LayoutGushitongRoute
  '/icons': typeof LayoutIconsRoute
  '/table-basic': typeof LayoutTableBasicRoute
  '/table-pagination': typeof LayoutTablePaginationRoute
  '/tests': typeof LayoutTestsRoute
  '/text': typeof LayoutTextRoute
  '/valtio': typeof LayoutValtioRoute
  '/invoices/$invoiceId': typeof AuthInvoicesInvoiceIdRoute
  '/echarts/btcusdt': typeof LayoutEchartsBtcusdtRoute
  '/echarts/crypto': typeof LayoutEchartsCryptoRoute
  '/echarts/gushi': typeof LayoutEchartsGushiRoute
  '/g2/candle-sticks': typeof LayoutG2CandleSticksRoute
  '/g2/kline': typeof LayoutG2KlineRoute
  '/g2/multi-area': typeof LayoutG2MultiAreaRoute
  '/g2/slider': typeof LayoutG2SliderRoute
  '/g2/spot': typeof LayoutG2SpotRoute
  '/g2/tooltip': typeof LayoutG2TooltipRoute
  '/invoices/': typeof AuthInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/bitget-grid': typeof LayoutBitgetGridRoute
  '/bitget-sf': typeof LayoutBitgetSfRoute
  '/coingecko': typeof LayoutCoingeckoRoute
  '/cron-api': typeof LayoutCronApiRoute
  '/cron-config': typeof LayoutCronConfigRoute
  '/cron-jobs': typeof LayoutCronJobsRoute
  '/cron-logs': typeof LayoutCronLogsRoute
  '/cron-worker': typeof LayoutCronWorkerRoute
  '/fear-greed': typeof LayoutFearGreedRoute
  '/gate-grid': typeof LayoutGateGridRoute
  '/gushitong': typeof LayoutGushitongRoute
  '/icons': typeof LayoutIconsRoute
  '/table-basic': typeof LayoutTableBasicRoute
  '/table-pagination': typeof LayoutTablePaginationRoute
  '/tests': typeof LayoutTestsRoute
  '/text': typeof LayoutTextRoute
  '/valtio': typeof LayoutValtioRoute
  '/invoices/$invoiceId': typeof AuthInvoicesInvoiceIdRoute
  '/echarts/btcusdt': typeof LayoutEchartsBtcusdtRoute
  '/echarts/crypto': typeof LayoutEchartsCryptoRoute
  '/echarts/gushi': typeof LayoutEchartsGushiRoute
  '/g2/candle-sticks': typeof LayoutG2CandleSticksRoute
  '/g2/kline': typeof LayoutG2KlineRoute
  '/g2/multi-area': typeof LayoutG2MultiAreaRoute
  '/g2/slider': typeof LayoutG2SliderRoute
  '/g2/spot': typeof LayoutG2SpotRoute
  '/g2/tooltip': typeof LayoutG2TooltipRoute
  '/invoices': typeof AuthInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/invoices': typeof AuthInvoicesRouteWithChildren
  '/_layout/bitget-grid': typeof LayoutBitgetGridRoute
  '/_layout/bitget-sf': typeof LayoutBitgetSfRoute
  '/_layout/coingecko': typeof LayoutCoingeckoRoute
  '/_layout/cron-api': typeof LayoutCronApiRoute
  '/_layout/cron-config': typeof LayoutCronConfigRoute
  '/_layout/cron-jobs': typeof LayoutCronJobsRoute
  '/_layout/cron-logs': typeof LayoutCronLogsRoute
  '/_layout/cron-worker': typeof LayoutCronWorkerRoute
  '/_layout/fear-greed': typeof LayoutFearGreedRoute
  '/_layout/gate-grid': typeof LayoutGateGridRoute
  '/_layout/gushitong': typeof LayoutGushitongRoute
  '/_layout/icons': typeof LayoutIconsRoute
  '/_layout/table-basic': typeof LayoutTableBasicRoute
  '/_layout/table-pagination': typeof LayoutTablePaginationRoute
  '/_layout/tests': typeof LayoutTestsRoute
  '/_layout/text': typeof LayoutTextRoute
  '/_layout/valtio': typeof LayoutValtioRoute
  '/_auth/invoices/$invoiceId': typeof AuthInvoicesInvoiceIdRoute
  '/_layout/echarts/btcusdt': typeof LayoutEchartsBtcusdtRoute
  '/_layout/echarts/crypto': typeof LayoutEchartsCryptoRoute
  '/_layout/echarts/gushi': typeof LayoutEchartsGushiRoute
  '/_layout/g2/candle-sticks': typeof LayoutG2CandleSticksRoute
  '/_layout/g2/kline': typeof LayoutG2KlineRoute
  '/_layout/g2/multi-area': typeof LayoutG2MultiAreaRoute
  '/_layout/g2/slider': typeof LayoutG2SliderRoute
  '/_layout/g2/spot': typeof LayoutG2SpotRoute
  '/_layout/g2/tooltip': typeof LayoutG2TooltipRoute
  '/_auth/invoices/': typeof AuthInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/dashboard'
    | '/invoices'
    | '/bitget-grid'
    | '/bitget-sf'
    | '/coingecko'
    | '/cron-api'
    | '/cron-config'
    | '/cron-jobs'
    | '/cron-logs'
    | '/cron-worker'
    | '/fear-greed'
    | '/gate-grid'
    | '/gushitong'
    | '/icons'
    | '/table-basic'
    | '/table-pagination'
    | '/tests'
    | '/text'
    | '/valtio'
    | '/invoices/$invoiceId'
    | '/echarts/btcusdt'
    | '/echarts/crypto'
    | '/echarts/gushi'
    | '/g2/candle-sticks'
    | '/g2/kline'
    | '/g2/multi-area'
    | '/g2/slider'
    | '/g2/spot'
    | '/g2/tooltip'
    | '/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/dashboard'
    | '/bitget-grid'
    | '/bitget-sf'
    | '/coingecko'
    | '/cron-api'
    | '/cron-config'
    | '/cron-jobs'
    | '/cron-logs'
    | '/cron-worker'
    | '/fear-greed'
    | '/gate-grid'
    | '/gushitong'
    | '/icons'
    | '/table-basic'
    | '/table-pagination'
    | '/tests'
    | '/text'
    | '/valtio'
    | '/invoices/$invoiceId'
    | '/echarts/btcusdt'
    | '/echarts/crypto'
    | '/echarts/gushi'
    | '/g2/candle-sticks'
    | '/g2/kline'
    | '/g2/multi-area'
    | '/g2/slider'
    | '/g2/spot'
    | '/g2/tooltip'
    | '/invoices'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_layout'
    | '/about'
    | '/login'
    | '/_auth/dashboard'
    | '/_auth/invoices'
    | '/_layout/bitget-grid'
    | '/_layout/bitget-sf'
    | '/_layout/coingecko'
    | '/_layout/cron-api'
    | '/_layout/cron-config'
    | '/_layout/cron-jobs'
    | '/_layout/cron-logs'
    | '/_layout/cron-worker'
    | '/_layout/fear-greed'
    | '/_layout/gate-grid'
    | '/_layout/gushitong'
    | '/_layout/icons'
    | '/_layout/table-basic'
    | '/_layout/table-pagination'
    | '/_layout/tests'
    | '/_layout/text'
    | '/_layout/valtio'
    | '/_auth/invoices/$invoiceId'
    | '/_layout/echarts/btcusdt'
    | '/_layout/echarts/crypto'
    | '/_layout/echarts/gushi'
    | '/_layout/g2/candle-sticks'
    | '/_layout/g2/kline'
    | '/_layout/g2/multi-area'
    | '/_layout/g2/slider'
    | '/_layout/g2/spot'
    | '/_layout/g2/tooltip'
    | '/_auth/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/valtio': {
      id: '/_layout/valtio'
      path: '/valtio'
      fullPath: '/valtio'
      preLoaderRoute: typeof LayoutValtioRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/text': {
      id: '/_layout/text'
      path: '/text'
      fullPath: '/text'
      preLoaderRoute: typeof LayoutTextRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tests': {
      id: '/_layout/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof LayoutTestsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/table-pagination': {
      id: '/_layout/table-pagination'
      path: '/table-pagination'
      fullPath: '/table-pagination'
      preLoaderRoute: typeof LayoutTablePaginationRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/table-basic': {
      id: '/_layout/table-basic'
      path: '/table-basic'
      fullPath: '/table-basic'
      preLoaderRoute: typeof LayoutTableBasicRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/icons': {
      id: '/_layout/icons'
      path: '/icons'
      fullPath: '/icons'
      preLoaderRoute: typeof LayoutIconsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/gushitong': {
      id: '/_layout/gushitong'
      path: '/gushitong'
      fullPath: '/gushitong'
      preLoaderRoute: typeof LayoutGushitongRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/gate-grid': {
      id: '/_layout/gate-grid'
      path: '/gate-grid'
      fullPath: '/gate-grid'
      preLoaderRoute: typeof LayoutGateGridRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/fear-greed': {
      id: '/_layout/fear-greed'
      path: '/fear-greed'
      fullPath: '/fear-greed'
      preLoaderRoute: typeof LayoutFearGreedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cron-worker': {
      id: '/_layout/cron-worker'
      path: '/cron-worker'
      fullPath: '/cron-worker'
      preLoaderRoute: typeof LayoutCronWorkerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cron-logs': {
      id: '/_layout/cron-logs'
      path: '/cron-logs'
      fullPath: '/cron-logs'
      preLoaderRoute: typeof LayoutCronLogsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cron-jobs': {
      id: '/_layout/cron-jobs'
      path: '/cron-jobs'
      fullPath: '/cron-jobs'
      preLoaderRoute: typeof LayoutCronJobsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cron-config': {
      id: '/_layout/cron-config'
      path: '/cron-config'
      fullPath: '/cron-config'
      preLoaderRoute: typeof LayoutCronConfigRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cron-api': {
      id: '/_layout/cron-api'
      path: '/cron-api'
      fullPath: '/cron-api'
      preLoaderRoute: typeof LayoutCronApiRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/coingecko': {
      id: '/_layout/coingecko'
      path: '/coingecko'
      fullPath: '/coingecko'
      preLoaderRoute: typeof LayoutCoingeckoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/bitget-sf': {
      id: '/_layout/bitget-sf'
      path: '/bitget-sf'
      fullPath: '/bitget-sf'
      preLoaderRoute: typeof LayoutBitgetSfRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/bitget-grid': {
      id: '/_layout/bitget-grid'
      path: '/bitget-grid'
      fullPath: '/bitget-grid'
      preLoaderRoute: typeof LayoutBitgetGridRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_auth/invoices': {
      id: '/_auth/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthInvoicesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/invoices/': {
      id: '/_auth/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthInvoicesIndexRouteImport
      parentRoute: typeof AuthInvoicesRoute
    }
    '/_layout/g2/tooltip': {
      id: '/_layout/g2/tooltip'
      path: '/g2/tooltip'
      fullPath: '/g2/tooltip'
      preLoaderRoute: typeof LayoutG2TooltipRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/g2/spot': {
      id: '/_layout/g2/spot'
      path: '/g2/spot'
      fullPath: '/g2/spot'
      preLoaderRoute: typeof LayoutG2SpotRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/g2/slider': {
      id: '/_layout/g2/slider'
      path: '/g2/slider'
      fullPath: '/g2/slider'
      preLoaderRoute: typeof LayoutG2SliderRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/g2/multi-area': {
      id: '/_layout/g2/multi-area'
      path: '/g2/multi-area'
      fullPath: '/g2/multi-area'
      preLoaderRoute: typeof LayoutG2MultiAreaRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/g2/kline': {
      id: '/_layout/g2/kline'
      path: '/g2/kline'
      fullPath: '/g2/kline'
      preLoaderRoute: typeof LayoutG2KlineRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/g2/candle-sticks': {
      id: '/_layout/g2/candle-sticks'
      path: '/g2/candle-sticks'
      fullPath: '/g2/candle-sticks'
      preLoaderRoute: typeof LayoutG2CandleSticksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/echarts/gushi': {
      id: '/_layout/echarts/gushi'
      path: '/echarts/gushi'
      fullPath: '/echarts/gushi'
      preLoaderRoute: typeof LayoutEchartsGushiRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/echarts/crypto': {
      id: '/_layout/echarts/crypto'
      path: '/echarts/crypto'
      fullPath: '/echarts/crypto'
      preLoaderRoute: typeof LayoutEchartsCryptoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/echarts/btcusdt': {
      id: '/_layout/echarts/btcusdt'
      path: '/echarts/btcusdt'
      fullPath: '/echarts/btcusdt'
      preLoaderRoute: typeof LayoutEchartsBtcusdtRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_auth/invoices/$invoiceId': {
      id: '/_auth/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AuthInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthInvoicesRoute
    }
  }
}

interface AuthInvoicesRouteChildren {
  AuthInvoicesInvoiceIdRoute: typeof AuthInvoicesInvoiceIdRoute
  AuthInvoicesIndexRoute: typeof AuthInvoicesIndexRoute
}

const AuthInvoicesRouteChildren: AuthInvoicesRouteChildren = {
  AuthInvoicesInvoiceIdRoute: AuthInvoicesInvoiceIdRoute,
  AuthInvoicesIndexRoute: AuthInvoicesIndexRoute,
}

const AuthInvoicesRouteWithChildren = AuthInvoicesRoute._addFileChildren(
  AuthInvoicesRouteChildren,
)

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthInvoicesRoute: typeof AuthInvoicesRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthInvoicesRoute: AuthInvoicesRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LayoutRouteChildren {
  LayoutBitgetGridRoute: typeof LayoutBitgetGridRoute
  LayoutBitgetSfRoute: typeof LayoutBitgetSfRoute
  LayoutCoingeckoRoute: typeof LayoutCoingeckoRoute
  LayoutCronApiRoute: typeof LayoutCronApiRoute
  LayoutCronConfigRoute: typeof LayoutCronConfigRoute
  LayoutCronJobsRoute: typeof LayoutCronJobsRoute
  LayoutCronLogsRoute: typeof LayoutCronLogsRoute
  LayoutCronWorkerRoute: typeof LayoutCronWorkerRoute
  LayoutFearGreedRoute: typeof LayoutFearGreedRoute
  LayoutGateGridRoute: typeof LayoutGateGridRoute
  LayoutGushitongRoute: typeof LayoutGushitongRoute
  LayoutIconsRoute: typeof LayoutIconsRoute
  LayoutTableBasicRoute: typeof LayoutTableBasicRoute
  LayoutTablePaginationRoute: typeof LayoutTablePaginationRoute
  LayoutTestsRoute: typeof LayoutTestsRoute
  LayoutTextRoute: typeof LayoutTextRoute
  LayoutValtioRoute: typeof LayoutValtioRoute
  LayoutEchartsBtcusdtRoute: typeof LayoutEchartsBtcusdtRoute
  LayoutEchartsCryptoRoute: typeof LayoutEchartsCryptoRoute
  LayoutEchartsGushiRoute: typeof LayoutEchartsGushiRoute
  LayoutG2CandleSticksRoute: typeof LayoutG2CandleSticksRoute
  LayoutG2KlineRoute: typeof LayoutG2KlineRoute
  LayoutG2MultiAreaRoute: typeof LayoutG2MultiAreaRoute
  LayoutG2SliderRoute: typeof LayoutG2SliderRoute
  LayoutG2SpotRoute: typeof LayoutG2SpotRoute
  LayoutG2TooltipRoute: typeof LayoutG2TooltipRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBitgetGridRoute: LayoutBitgetGridRoute,
  LayoutBitgetSfRoute: LayoutBitgetSfRoute,
  LayoutCoingeckoRoute: LayoutCoingeckoRoute,
  LayoutCronApiRoute: LayoutCronApiRoute,
  LayoutCronConfigRoute: LayoutCronConfigRoute,
  LayoutCronJobsRoute: LayoutCronJobsRoute,
  LayoutCronLogsRoute: LayoutCronLogsRoute,
  LayoutCronWorkerRoute: LayoutCronWorkerRoute,
  LayoutFearGreedRoute: LayoutFearGreedRoute,
  LayoutGateGridRoute: LayoutGateGridRoute,
  LayoutGushitongRoute: LayoutGushitongRoute,
  LayoutIconsRoute: LayoutIconsRoute,
  LayoutTableBasicRoute: LayoutTableBasicRoute,
  LayoutTablePaginationRoute: LayoutTablePaginationRoute,
  LayoutTestsRoute: LayoutTestsRoute,
  LayoutTextRoute: LayoutTextRoute,
  LayoutValtioRoute: LayoutValtioRoute,
  LayoutEchartsBtcusdtRoute: LayoutEchartsBtcusdtRoute,
  LayoutEchartsCryptoRoute: LayoutEchartsCryptoRoute,
  LayoutEchartsGushiRoute: LayoutEchartsGushiRoute,
  LayoutG2CandleSticksRoute: LayoutG2CandleSticksRoute,
  LayoutG2KlineRoute: LayoutG2KlineRoute,
  LayoutG2MultiAreaRoute: LayoutG2MultiAreaRoute,
  LayoutG2SliderRoute: LayoutG2SliderRoute,
  LayoutG2SpotRoute: LayoutG2SpotRoute,
  LayoutG2TooltipRoute: LayoutG2TooltipRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
